version: '3.8'
services:
  app:
    build: .
    command: npm start
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      DATABASE_URL: postgres://user:password@db:5432/social_network_db
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis_container
    ports:
      - '6379:6379'
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: social_network_db
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5433:5432'
    networks:
      - app-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: redis
    ports:
      - "8081:8081"
    depends_on:
      - redis

networks:
  app-network:
    driver: bridge
