### Create new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "Test",
  "password": "password test"
}

### Login user and get tokens
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "Test",
  "password": "password test"
}

### Get Token by username
GET http://localhost:3000/auth/get-token/Test
Content-Type: application/json

### Create Post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "content": "test content redis 2",
  "title": "test title redis 2",
  "user_id": 1
}

### Get Posts
GET http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJzdWIiOjUsImlhdCI6MTczMzA2ODYyNiwiZXhwIjoxNzMzMDc5NDI2fQ.NAztKUOmWs2Qc7YCbAVOnK5JIuBuPdeLjI6f9bNINVE
