CREATE TABLE IF NOT EXISTS Users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    password VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS POSTS (
    id SERIAL PRIMARY KEY,
    content TEXT NOT NULL,
    title VARCHAR(100) NOT NULL,
    userId NUMERIC,
    FOREIGN KEY (userId) REFERENCES Users(id)
);
